const directory = {
  text: "Rust基础",
  items: [
    { text: "前言", link: "/Rust/0.前言" },
    { text: "Rust介绍", link: "/Rust/1.0.rust介绍" },
    { text: "安装并创建项目", link: "/Rust/1.1.安装并创建项目" },
    { text: "打印和格式化", link: "/Rust/1.2.打印和格式化" },
    { text: "变量和可变性", link: "/Rust/2.变量和可变性" },
    { text: "数据类型", link: "/Rust/3.1.数据类型" },
    { text: "控制流", link: "/Rust/3.2.控制流" },
    { text: "函数", link: "/Rust/4.函数" },
    { text: "指针", link: "/Rust/5.0.指针" },
    { text: "所有权", link: "/Rust/5.1.所有权" },
    { text: "所有权延申", link: "/Rust/5.2.所有权延申" },
    { text: "Slice切片", link: "/Rust/5.3.Slice切片" },
    { text: "struct结构体", link: "/Rust/6.struct结构体" },
    { text: "enum枚举", link: "/Rust/7.enum枚举" },
    { text: "match模式匹配", link: "/Rust/8.1.match模式匹配" },
    { text: "模式与模式匹配", link: "/Rust/8.2.模式与模式匹配" },
    { text: "模块系统", link: "/Rust/9.模块系统" },
    { text: "vector向量", link: "/Rust/10.vector向量" },
    { text: "String字符串", link: "/Rust/11.1.String字符串" },
    { text: "String延申", link: "/Rust/11.2.String延申" },
    { text: "HashMap哈希表", link: "/Rust/12.哈希map" },
    { text: "错误处理", link: "/Rust/13.错误处理" },
    { text: "泛型", link: "/Rust/14.1.泛型" },
    { text: "Trait特征", link: "/Rust/14.2.Trait特征" },
    { text: "生命周期", link: "/Rust/15.生命周期" },
    { text: "自动化测试", link: "/Rust/16.编写自动化测试" },
    { text: "闭包和迭代器", link: "/Rust/17.闭包和迭代器" },
    { text: "Cargo和Crates.io", link: "/Rust/18.Cargo和Crates.io" },
    { text: "智能指针", link: "/Rust/19.1.智能指针" },
    { text: "智能指针总结", link: "/Rust/19.2.智能指针总结" },
    { text: "无畏并发", link: "/Rust/20.1.无畏并发" },
    { text: "无畏并发延申", link: "/Rust/20.2.无畏并发延申" },
    { text: "异步编程", link: "/Rust/21.1.异步编程" },
    { text: "异步编程延申", link: "/Rust/21.2.异步编程延申" },
    { text: "面向对象编程", link: "/Rust/22.1.面向对象编程" },
    { text: "不安全 Rust", link: "/Rust/23.1.unsafeRust" },
    { text: "高级 Trait", link: "/Rust/24.1.高级trait" },
    { text: "高级 类型", link: "/Rust/25.1.高级类型" },
    { text: "高级函数和闭包", link: "/Rust/26.1.高级函数和闭包" },
    { text: "Macro宏", link: "/Rust/27.1.Macro宏" },
  ],
};
export default directory;
