const directory = {
  text: "Rust基础",
  items: [
    { text: "前言", link: "/Rust/前言" },
    { text: "学习资料", link: "/Rust/学习资料" },
    { text: "Rust介绍", link: "/Rust/rust介绍" },
    { text: "安装并创建项目", link: "/Rust/安装并创建项目" },
    { text: "注释", link: "/Rust/注释" },
    { text: "打印", link: "/Rust/打印" },
    { text: "语句和表达式", link: "/Rust/语句和表达式" },
    { text: "变量和可变性", link: "/Rust/变量和可变性" },
    { text: "原生数据类型", link: "/Rust/原生数据类型" },
    { text: "函数", link: "/Rust/函数" },
    { text: "控制流", link: "/Rust/控制流" },
    { text: "内存和指针", link: "/Rust/内存和指针" },
    { text: "作用域", link: "/Rust/作用域" },
    { text: "所有权", link: "/Rust/所有权" },
    { text: "所有权延申", link: "/Rust/所有权延申" },
    { text: "Slice切片", link: "/Rust/Slice切片" },
    { text: "Struct结构体", link: "/Rust/struct结构体" },
    { text: "Enum枚举", link: "/Rust/enum枚举" },
    { text: "模式与模式匹配", link: "/Rust/模式与模式匹配" },
    { text: "Vector向量", link: "/Rust/vector向量" },
    { text: "String字符串", link: "/Rust/String字符串" },
    { text: "String延申", link: "/Rust/String延申" },
    { text: "HashMap哈希表", link: "/Rust/HashMap哈希表" },
    { text: "包、Crates 与模块", link: "/Rust/包、Crates 与模块" },
    { text: "错误处理", link: "/Rust/错误处理" },
    { text: "泛型", link: "/Rust/泛型" },
    { text: "Trait特征", link: "/Rust/Trait特征" },
    { text: "高级 Trait", link: "/Rust/高级trait" },
    { text: "生命周期", link: "/Rust/生命周期" },
    { text: "自动化测试", link: "/Rust/自动化测试" },
    { text: "闭包", link: "/Rust/闭包" },
    { text: "迭代器", link: "/Rust/迭代器" },
    { text: "Cargo和Crates.io", link: "/Rust/Cargo和Crates.io" },
    { text: "智能指针", link: "/Rust/智能指针" },
    { text: "智能指针总结", link: "/Rust/智能指针总结" },
    { text: "无畏并发", link: "/Rust/无畏并发" },
    { text: "无畏并发延申", link: "/Rust/无畏并发延申" },
    { text: "异步编程", link: "/Rust/异步编程" },
    { text: "异步编程延申", link: "/Rust/异步编程延申" },
    { text: "面向对象编程", link: "/Rust/面向对象编程" },
    { text: "不安全 Rust", link: "/Rust/unsafeRust" },
    { text: "高级 类型", link: "/Rust/高级类型" },
    { text: "高级函数和闭包", link: "/Rust/高级函数和闭包" },
    { text: "Macro宏", link: "/Rust/Macro宏" },
  ],
};
export default directory;
